steps:
  - name: node
    entrypoint: npm
    args: ['install', './frontend/package.json']
  - name: node
    entrypoint: npm
    args: ['test']
  - name: node
    entrypoint: npm
    args: ['run', 'build']