steps:
  - name: 'bash'
    args: ['echo', 'Let us begin!']
  - name: 'gcr.io/cloud-builders/git'
    secretEnv: ['SSH_KEY']
    entrypoint: 'bash'
    args:
      - -c
      - |
        echo "$$SSH_KEY" >> /root/.ssh/id_rsa
        chmod 400 /root/.ssh/id_rsa
        cp known_hosts.github /root/.ssh/known_hosts
    volumes:
      - name: 'ssh'
        path: /root/.ssh

  # Clone the repository
  - name: 'gcr.io/cloud-builders/git'
    args:
      - clone
      - --recurse-submodules
      - git@github.com:simongottipalli/uuid-gen
    volumes:
      - name: 'ssh'
      - path: /root/.ssh
availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/git-access/versions/latest
      env: 'SSH_KEY'
#  - name: 'bash'
#    args: ['cd', 'frontend']
#  - name: 'npm'
#    args: [ 'run', 'build' ]
#  - name: 'bash'
#    args: ['cp', '-r', 'build', '.docker']
#  - name: 'bash'
#    args: [ 'cd', '.docker' ]
#  - name: 'gcr.io/cloud-builders/docker'
#    args: [ 'build', '-t', 'europe-west1-docker.pkg.dev/$PROJECT_ID/docker-builds/frontend', '.' ]
#  - name: 'gcr.io/cloud-builders/docker'
#    args: ['push', 'europe-west1-docker.pkg.dev/$PROJECT_ID/docker-builds/frontend']
#  - name: 'gcr.io/cloud-builders/gcloud'
#    args:
#      - 'run'
#      - 'deploy'
#      - 'cloudrunservice'
#      - '--image'
#      - 'europe-west1-docker.pkg.dev/$PROJECT_ID/docker-builds/frontend'
#      - '--region'
#      - 'europe-west1'
#      - '--platform'
#      - 'managed'
#      - '--allow-unauthenticated'
#images:
#  - 'europe-west1-docker.pkg.dev/$PROJECT_ID/docker-builds/frontend'