steps:
  - name: node
    entrypoint: npm
    args: ['install', './frontend']
#  - name: node
#    entrypoint: npm
#    args: ['test', '--prefix', './frontend']
  - name: node
    entrypoint: npm
    args: ['run', 'build', '--prefix', './frontend']