swagger: "2.0"
info:
  title: UUID Generator
  description: Generates one or more UUIDs
  version: 0.0.4
host: 0.0.0.0:8080
paths:
  /:
    get:
      summary: readiness check
      description: readiness check
      responses:
        200:    # status code
          $ref: '#/responses/200'
  /uuid/{version}:
    get:
      summary: Get a uuid
      description: A single UUID
      produces:
        - application/json
      parameters:
        - $ref: '#/parameters/version'
        - $ref: '#/parameters/name'
        - $ref: '#/parameters/uuid'
      responses:
        200:
          description: Successfully return a uuid
          schema:
            $ref: '#/definitions/GetUUIDResponse'
        500:
          $ref: '#/responses/500'

responses:
  200:
    description: Success
  500:
    description: Error
    schema:
      $ref: '#/definitions/Error'

definitions:
  GetUUIDResponse:
    type: object
    required:
      - uuid
    properties:
      uuid:
        type: string
  Error:
    type: object
    properties:
      error:
        type: string
        description: OK

parameters:
  version:
    in: path
    name: version
    type: string
    enum:
      - v1
      - v2
      - v3
      - v4
      - v5
    required: true
    description: |
      UUID version
  name:
    in: query
    type: string
    required: false
    name: name
    description: |
      A name string for UUID V3
  uuid:
    in: query
    type: string
    required: false
    name: uuid
    description: |
      Predefined UUID for a V3 UUID
