swagger: "2.0"
info:
  title: UUID Generator
  description: Generates one or more UUIDs
  version: 0.0.1

# host: api.example.com
basePath: /v1
schemes:
  - http

paths:
  /uuid:
    get:
      summary: Returns a uuid
      description: Description
      produces:
        - application/json
      responses:
        200:    # status code
          description: A single UUID
          schema:
            type: object
            $ref: '#/definitions/GetUUIDResponse'
        default:
          description: fails
          schema:
            type: object
            $ref: '#/definitions/Error'

definitions:
  GetUUIDResponse:
    type: object
    required:
      - uuid
    properties:
      uuid:
        type: string
  Error:
    type: object
    required:
      - error
    properties:
      error:
        type: string