swagger: "2.0"
info:
  title: UUID Generator
  description: Generates one or more UUIDs
  version: 0.0.2
host: 0.0.0.0:8080
paths:
  /:
    get:
      summary: readiness check
      description: readiness check
      responses:
        200:    # status code
          description: OK
responses:
  200:
    description: Success
