// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// GetReadinessCheckOKCode is the HTTP code returned for type GetReadinessCheckOK
const GetReadinessCheckOKCode int = 200

/*GetReadinessCheckOK OK

swagger:response getReadinessCheckOK
*/
type GetReadinessCheckOK struct {
}

// NewGetReadinessCheckOK creates GetReadinessCheckOK with default headers values
func NewGetReadinessCheckOK() *GetReadinessCheckOK {

	return &GetReadinessCheckOK{}
}

// WriteResponse to the client
func (o *GetReadinessCheckOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}
