// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// GetUUIDOKCode is the HTTP code returned for type GetUUIDOK
const GetUUIDOKCode int = 200

/*GetUUIDOK A single UUID

swagger:response getUuidOK
*/
type GetUUIDOK struct {
}

// NewGetUUIDOK creates GetUUIDOK with default headers values
func NewGetUUIDOK() *GetUUIDOK {

	return &GetUUIDOK{}
}

// WriteResponse to the client
func (o *GetUUIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}
