// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "Generates one or more UUIDs",
    "title": "UUID Generator",
    "version": "0.0.1"
  },
  "basePath": "/v1",
  "paths": {
    "/uuid": {
      "get": {
        "description": "Description",
        "produces": [
          "application/json"
        ],
        "summary": "Returns a uuid",
        "responses": {
          "200": {
            "description": "A single UUID",
            "schema": {
              "type": "object",
              "$ref": "#/definitions/GetUUIDResponse"
            }
          },
          "default": {
            "description": "fails",
            "schema": {
              "type": "object",
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "Error": {
      "type": "object",
      "required": [
        "error"
      ],
      "properties": {
        "error": {
          "type": "string"
        }
      }
    },
    "GetUUIDResponse": {
      "type": "object",
      "required": [
        "uuid"
      ],
      "properties": {
        "uuid": {
          "type": "string"
        }
      }
    }
  }
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "Generates one or more UUIDs",
    "title": "UUID Generator",
    "version": "0.0.1"
  },
  "basePath": "/v1",
  "paths": {
    "/uuid": {
      "get": {
        "description": "Description",
        "produces": [
          "application/json"
        ],
        "summary": "Returns a uuid",
        "responses": {
          "200": {
            "description": "A single UUID",
            "schema": {
              "type": "object",
              "$ref": "#/definitions/GetUUIDResponse"
            }
          },
          "default": {
            "description": "fails",
            "schema": {
              "type": "object",
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "Error": {
      "type": "object",
      "required": [
        "error"
      ],
      "properties": {
        "error": {
          "type": "string"
        }
      }
    },
    "GetUUIDResponse": {
      "type": "object",
      "required": [
        "uuid"
      ],
      "properties": {
        "uuid": {
          "type": "string"
        }
      }
    }
  }
}`))
}
