name: Backend - Build and Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  PROJECT_ID: uuid-gen
  RUN_REGION: europe-west1
  SERVICE_NAME: uuid-gen

jobs:
  test:
    name: Run Tests 🧪
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...
  build:
    name: Build Backend ⚒️
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@main

      - name: Setup GCloud Auth
        id: auth
        uses: google-github-actions/auth@v0.4.0
        with:
          credentials_json: ${{ secrets.GCR_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.1

      - name: Build & Push
        run: |-
          gcloud builds submit --tag "europe-west1-docker.pkg.dev/$PROJECT_ID/docker-builds/uuid-gen"

  deploy-gcr:
    name: Deploy to GCP 🚀
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Setup GCloud Auth
        id: auth
        uses: google-github-actions/auth@v0.4.0
        with:
          credentials_json: ${{ secrets.GCR_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.1

      # Deploy image to Cloud Run
      - name: Deploy GCR
        run: |-
          gcloud run deploy $SERVICE_NAME \
            --quiet \
            --region "$RUN_REGION" \
            --image "europe-west1-docker.pkg.dev/$PROJECT_ID/docker-builds/uuid-gen" \
            --platform "managed" \
            --allow-unauthenticated